#!/usr/bin/env bash                                                                                                                                       
# This script installs and configures Nginx to listen on port 80                                                                                                        # Go to sites-enabled folder for Nginx                                                                                                                    
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
# Delete the default file                                                                                                                               
rm default;                                                                                                                                               
# Create symbolic link to the deafult file in sites-available                                                                                             
ln -s /etc/nginx/sites-available/default default;                                                                                                         
# Restart Nginx                                                                                                                                           
service nginx restart 
