#!/usr/bin/env bash
# Check if nginx is running and start it if not
if ! service nginx status | grep -q "nginx is running"; then
    service nginx start
fi
curl -sI http://localhost | grep -q "200 OK"
