#!/usr/bin/env bash
# Sets the nginx server to listen on port 80 for all active IPv4 addresses

sudo sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
sudo truncate -s 0 /run/nginx.pid
